/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gulei_ffmpegandroid_FFmpegUtil */

#ifndef _Included_com_gulei_ffmpegandroid_FFmpegUtil
#define _Included_com_gulei_ffmpegandroid_FFmpegUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gulei_ffmpegandroid_FFmpegUtil
 * Method:    run
 * Signature: (I[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_gulei_ffmpegandroid_FFmpegUtil_run
  (JNIEnv *, jclass, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
