/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gulei_ffmpegandroid_ApiPlayer */

#ifndef _Included_com_gulei_ffmpegandroid_ApiPlayer
#define _Included_com_gulei_ffmpegandroid_ApiPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gulei_ffmpegandroid_ApiPlayer
 * Method:    jnitest
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gulei_ffmpegandroid_ApiPlayer_jnitest
  (JNIEnv *, jclass);

/*
 * Class:     com_gulei_ffmpegandroid_ApiPlayer
 * Method:    decodeVideo
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_gulei_ffmpegandroid_ApiPlayer_decodeVideo
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
